language: php

php:
  - 5.5

env:
  global:
    - HOST=www.simplemappr.local
    - IMGHOST=img.simplemappr.local
    - DBNAME=simplemappr_test

services:
  - redis-server

install:
  # Install dependencies
  - sh -e .travis/scripts/apt-get.sh

  # MapServer installation
  - sh -e .travis/scripts/mapserver.sh

  # Translations
  - sh -e .travis/scripts/locales.sh
  
  # Redis
  - sh -e .travis/scripts/php-redis.sh

before_script:
  # Directory permissions
  - sh -e .travis/scripts/perms.sh

  # Apache config
  - sh -e .travis/scripts/apache2-configure.sh

  # Apache web server config for vhosts
  - sh -e .travis/scripts/apache2-vhost.sh "$HOST"
  - sh -e .travis/scripts/apache2-vhost.sh "$IMGHOST"

  # PHP config
  - phpenv config-add .travis/travis.php.ini

  # MySQL
  - sh -e .travis/scripts/mysql-init.sh "$DBNAME"

  # Restart Apache
  - sudo service apache2 restart

  # Selenium
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.37.0.jar
  - java -jar selenium-server-standalone-2.37.0.jar > /dev/null &
  - sleep 15

script:
  - phpunit -c Tests/phpunit.xml --stderr
