language: php

php:
  - 5.6.29

env:
  global:
    - HOST=www.simplemappr.local
    - IMGHOST=img.simplemappr.local
    - DBNAME=simplemappr_testing
    - BROWSER=firefox

addons:
  firefox: "41.0.1"
  hosts:
    - www.simplemappr.local
    - img.simplemappr.local
  apt:
    packages:
      - apache2
      - build-essential
      - libapache2-mod-fastcgi
      - php5-cli
      - php5-common
      - php5-dev
      - php5-fpm
      - php5-gd
      - php5-mysql
      - php5-curl
      - locales
      - gettext
      - autoconf
      - libjpeg-dev
      - libpng12-dev
      - libfcgi-dev
      - libgdal1-dev
      - libgdal-dev
      - libproj-dev
      - libxml2-dev
      - libgeos-dev
      - libcairo2-dev
      - libfribidi-dev
      - imagemagick
      - libgtk2.0-0
      - xvfb
      - unzip
      - openjdk-7-jre
      - libmagickwand-dev
      - curl
      - cmake

install:
  # ImageMagick
  - printf "\n" | pecl install imagick

  # MapServer installation
  - sh -e .travis/scripts/mapserver.sh

  # PHP configuration
  - sh -e .travis/scripts/php.sh

  # Translations
  - sh -e .travis/scripts/locales.sh

  # PHP-FPM configuration
  - sh -e .travis/scripts/php-fpm.sh

  # Install maps
  - sh -e .travis/scripts/maps.sh

  # Install Composer dependencies
  - composer self-update
  - composer global require hirak/prestissimo
  - composer install

before_script:
  # Create files
  - sudo touch log/logger.log
  - sudo cp config/conf.test.php config/conf.php

  # Directory permissions
  - sh -e .travis/scripts/permissions.sh

  # Apache web server config for vhosts
  - sh -e .travis/scripts/apache-vhosts.sh

  # MySQL
  - sudo cp config/phinx.yml.sample config/phinx.yml
  - sh -e .travis/scripts/mysql-init.sh "$DBNAME"

  # Map files
  - sudo cp config/shapefiles.yml.sample config/shapefiles.yml

  # Restart PHP-FCGI and Apache
  - phpenv rehash
  - sudo service apache2 restart

  # Selenium
  - sh -e .travis/scripts/selenium.sh
  - sleep 3

script:
  - travis_retry php vendor/bin/phpunit -c Tests/$BROWSER.phpunit.xml --stderr

after_success:
  - travis_retry php vendor/bin/coveralls -c .coveralls.yml -v