language: php

php:
  - 5.5

env:
  global:
    - HOST=www.simplemappr.local
    - IMGHOST=img.simplemappr.local
    - DBNAME=simplemappr_test

services:
  - redis-server
      
before_install:
  # Directory permissions
  - sh -e .travis/scripts/perms.sh

  # Install dependencies
  - sh -e .travis/scripts/apt-get.sh

  # Apache config
  - sh -e .travis/scripts/apache2-configure.sh

  # Apache web server config for vhosts
  - sh -e .travis/scripts/apache2-vhost.sh "$HOST"
  - sh -e .travis/scripts/apache2-vhost.sh "$IMGHOST"

  # MapServer installation
  - sh -e .travis/scripts/mapserver.sh

  # Translations
  - sh -e .travis/scripts/translations.sh

  # MySQL
  - sh -e .travis/scripts/mysql-init.sh "$DBNAME"
  
  # Redis
  - sh -e .travis/scripts/redis.sh

  # Additional PHP config
  - phpenv config-add .travis/travis.php.ini
  
  # Restart Apache
  - sudo service apache2 restart

  # Selenium
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - curl http://selenium.googlecode.com/files/selenium-server-standalone-2.37.0.jar > selenium.jar
  - sudo ln -s /usr/lib/firefox/firefox /usr/lib/firefox/firefox-bin
  - PATH=$PATH:/usr/lib/firefox java -Dwebdriver.chrome.driver=/usr/bin/firefox -jar selenium.jar > /dev/null &
  - sleep 15

script: phpunit --configuration Tests/phpunit.xml --stderr
