language: php

php:
  - 5.5
  - 5.4

env:
  global:
    - HOST=www.simplemappr.local
    - ALIAS=simplemappr.net
    - DBNAME=simplemappr_test

before_install:
  # Install dependencies
  - sh -e .travis/scripts/apt-get.sh

  # Apache web server config
  - sh -e .travis/scripts/apache2-vhost.sh "$HOST" "$ALIAS"

  # MapServer installation
  - sh -e .travis/scripts/mapserver.sh

  # MySQL
  - sh -e .travis/scripts/mysql-init.sh "$DBNAME"

script: phpunit --configuration config/phpunit.xml --stderr
