language: php

php:
  - 5.5
  - 5.4

env:
  - HOST=simplemappr.local
  - WEB=www.simplemappr.local
  - DB=simplemappr_test

before_install:
  # Install dependencies
  - sh -e .travis/scripts/apt-get/sh

  # Apache web server config
  - sh -e .travis/scripts/apache2-vhost.sh "$HOST"

  # MapServer installation
  - sh -e .travis/scripts/mapserver.sh

before_script:
  - composer self-update
  - composer install --dev --no-interaction --prefer-source
  - mysql -e "CREATE database IF NOT EXISTS $DB;" -uroot

script: phpunit --configuration config/phpunit.xml --stderr
