sudo: required
dist: trusty

language: php

php:
  - 5.6.30

env:
  global:
    - HOST=www.simplemappr.local
    - IMGHOST=img.simplemappr.local
    - DBNAME=simplemappr_testing
    - BROWSER=chrome

addons:
  hosts:
    - www.simplemappr.local
    - img.simplemappr.local
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - apache2
      - build-essential
      - libapache2-mod-fastcgi
      - locales
      - gettext
      - autoconf
      - libjpeg-dev
      - libpng12-dev
      - libfcgi-dev
      - libgdal1-dev
      - libgdal-dev
      - libproj-dev
      - libxml2-dev
      - libgeos-dev
      - libcairo2-dev
      - libfribidi-dev
      - imagemagick
      - libgtk2.0-0
      - oracle-java8-installer
      - oracle-java8-set-default
      - xvfb
      - unzip
      - libmagickwand-dev
      - curl
      - cmake

before_install:
  - sudo apt-get software-properties-common
  - sudo add-apt-repository -y ppa:ondrej/php
  - sudo apt-get -qq update
  - sudo apt-get install -y php5.6
  - sudo apt-get install php5.6-cli php5.6-common php5.6-dev php5.6-fpm php5.6-gd php5.6-mysql php5.6-curl php5.6-imagick
  - php -i

install:
  - chmod 775 $HOME

  # ImageMagick
  - printf "\n" | pecl install imagick

  # MapServer installation
  - sh -e .travis/scripts/mapserver.sh
  
  # PHP configuration
  - phpenv config-add .travis/travis.php.ini
  - phpenv rehash

  # Translations
  - sh -e .travis/scripts/locales.sh

  # PHP-FPM configuration
  - sh -e .travis/scripts/php-fpm.sh

  # Install maps
  - sh -e .travis/scripts/maps.sh

  # Install Composer dependencies
  - composer self-update
  - composer global require hirak/prestissimo
  - composer install
 
  # Screen
  - sudo chmod 777 /usr/bin/google-chrome
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - export DBUS_SESSION_BUS_ADDRESS=/dev/null
  - Xvfb :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &

before_script:
  # Create files
  - sudo touch log/logger.log
  - sudo cp config/conf.test.php config/conf.php

  # Directory permissions
  - sh -e .travis/scripts/permissions.sh

  # Apache web server config for vhosts
  - sh -e .travis/scripts/apache-vhosts.sh

  # MySQL
  - sudo cp config/phinx.yml.sample config/phinx.yml
  - sh -e .travis/scripts/mysql-init.sh "$DBNAME"

  # Map files
  - sudo cp config/shapefiles.yml.sample config/shapefiles.yml

  # Restart PHP-FCGI and Apache
  - phpenv rehash
  - sudo service apache2 restart

  # Selenium
  - sh -e .travis/scripts/selenium.sh
  - sleep 5
  - sh -e .travis/scripts/selenium-test.sh

script:
  - php vendor/bin/phpunit -c Tests/$BROWSER.phpunit.xml --stderr

after_failure:
  - sudo cat /var/log/apache2/error.log
  - sudo cat $TRAVIS_BUILD_DIR/php-fpm.log

after_success:
  - php vendor/bin/coveralls -c .coveralls.yml -v