language: php

php:
  - 5.5
  - 5.4

env:
  - DB=mysql

before_install:
  - sudo apt-get update
  - sudo apt-get install apache2
  - sudo apt-get install libapache2-mod-php5
  - sudo apt-get install autoconf
  - sudo apt-get install libjpeg-dev libjpeg-dev libpng12-dev freetype*
  - sudo apt-get install libgdal-dev libproj-dev libxml2-dev libgeos-dev
  - sudo apt-get install libcairo2-dev libfribidi-dev
  - sudo apt-get install cmake
  - wget http://download.osgeo.org/mapserver/mapserver-6.4.0.tar.gz
  - tar -zxvf mapserver-6.4.0.tar.gz
  - cmake -DWITH_KML=1 -DWITH_PHP=1 -DWITH_FCGI=0 -DWITH_SVGCAIRO=1
  - make && make install

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS simplemappr_test;" -uroot; fi

script: phpunit --configuration config/phpunit.xml --coverage-text
