language: php

php:
  - 5.5

env:
  global:
    - HOST=www.simplemappr.local
    - DBNAME=simplemappr_test

before_install:
  # Install dependencies
  - sh -e .travis/scripts/apt-get.sh

  # Apache web server config for vhost
  - sh -e .travis/scripts/apache2-vhost.sh "$HOST"
  
  # Apache config
  - sh -e .travis/scripts/apache2-configure.sh "$HOST"

  # MapServer installation
  - sh -e .travis/scripts/mapserver.sh
  
  # Translations
  - sh -e .travis/scripts/translations.sh

  # MySQL
  - sh -e .travis/scripts/mysql-init.sh "$DBNAME"
  
  # Create empty config files
  - touch config/conf.php
  - touch config/conf.db.php
  
  # Show PHP configuration
  - php -i

script: phpunit --configuration config/phpunit.xml --stderr
