language: php

php:
  - 5.5

env:
  global:
    - HOST=www.simplemappr.local
    - IMGHOST=img.simplemappr.local
    - DBNAME=simplemappr_test
    - BROWSER=firefox

addons:
  firefox: "29.0"

install:
  # Install dependencies
  - sh -e .travis/scripts/apt-get.sh

  # MapServer installation
  - sh -e .travis/scripts/mapserver.sh

  # Install maps
  - sh -e .travis/scripts/maps.sh

  # Translations
  - sh -e .travis/scripts/locales.sh

  # Composer
  - composer install

before_script:
  # Create log file
  - sudo touch log/logger.log

  # Directory permissions
  - sh -e .travis/scripts/permissions.sh

  # Apache config
  # enable php-fpm because Travis doesn't do libapache2-mod-php5
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sh -e .travis/scripts/apache2-configure.sh
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm

  # Apache web server config for vhosts
  - sh -e .travis/scripts/apache2-vhost.sh "$HOST"
  - sh -e .travis/scripts/apache2-vhost.sh "$IMGHOST"

  # PHP config
  - phpenv config-add .travis/travis.php.ini

  # MySQL
  - sh -e .travis/scripts/mysql-init.sh "$DBNAME"

  # Restart Apache
  - sudo service apache2 restart
  
  # Force build of js/css
  - #wget -q -O /dev/null "http://www.simplemappr.local"
  - wget "http://www.simplemappr.local"

  # Selenium
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "wget http://selenium-release.storage.googleapis.com/2.41/selenium-server-standalone-2.41.0.jar"
  # - "java -jar selenium-server-standalone-2.41.0.jar -Dwebdriver.chrome.driver=/usr/bin/chromedriver > /dev/null &"
  - "java -jar selenium-server-standalone-2.41.0.jar > /dev/null &"
  - sleep 10

script:
  # - phpunit -c Tests/chrome.phpunit.xml --stderr
  - ./vendor/bin/phpunit -c Tests/$BROWSER.phpunit.xml --stderr
