language: php

php:
  - 5.5

env:
  global:
    - HOST=www.simplemappr.local
    - IMGHOST=img.simplemappr.local
    - DBNAME=simplemappr_testing
    - BROWSER=chrome

addons:
  hosts:
    - www.simplemappr.local
    - img.simplemappr.local

install:
  # Install server dependencies
  - sh -e .travis/scripts/apt-get.sh

  # MapServer installation
  - sh -e .travis/scripts/mapserver.sh

  # Install maps
  - sh -e .travis/scripts/maps.sh

  # Translations
  - sh -e .travis/scripts/locales.sh

  # Install Composer dependencies
  - composer self-update
  - composer install

before_script:
  # Create files
  - sudo touch log/logger.log
  - sudo cp config/conf.test.php config/conf.php

  # Directory permissions
  - sh -e .travis/scripts/permissions.sh

  # Apache config
  # enable php-fpm because Travis doesn't do libapache2-mod-php5
  - #sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sh -e .travis/scripts/apache2-configure.sh
  - #echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - #~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm

  # Apache web server config for vhosts
  - sh -e .travis/scripts/apache2-vhost.sh "$HOST"
  - sh -e .travis/scripts/apache2-vhost.sh "$IMGHOST"

  # PHP config
  - phpenv config-add .travis/travis.php.ini
  - php -i

  # MySQL
  - sudo cp config/phinx.yml.sample config/phinx.yml
  - sh -e .travis/scripts/mysql-init.sh "$DBNAME"

  # Restart Apache
  - sudo service apache2 reload

  # Chrome Driver & Framebuffer
  - sh -e .travis/scripts/chrome.sh
  - sleep 3

script:
  - ./vendor/bin/phpunit -c Tests/$BROWSER.phpunit.xml --stderr

after_script:
  - ./vendor/bin/coveralls -c .coveralls.yml -v
