language: php

php:
  - 5.5

env:
  global:
    - HOST=www.simplemappr.local
    - IMGHOST=img.simplemappr.local
    - DBNAME=simplemappr_testing
    - BROWSER=firefox

addons:
  firefox: "41.0.1"
  hosts:
    - www.simplemappr.local
    - img.simplemappr.local

before_script:
  # Install server dependencies
  - sudo add-apt-repository -y ppa:ondrej/php5
  - sudo add-apt-repository -y ppa:ondrej/apache2
  - sudo apt-get update -q
  - sh -e .travis/scripts/apt-get.sh

  # MapServer installation
  - sh -e .travis/scripts/mapserver.sh

  # Install maps
  - sh -e .travis/scripts/maps.sh

  # Translations
  - sh -e .travis/scripts/locales.sh

  # Install Composer dependencies
  - composer self-update
  - composer install

  # Create files
  - sudo touch log/logger.log
  - sudo cp config/conf.test.php config/conf.php

  # Directory permissions
  - sh -e .travis/scripts/permissions.sh

  # Apache config
  # enable php-fpm because Travis doesn't do libapache2-mod-php5
  - sh -e .travis/scripts/apache2-configure.sh

  # Apache web server config for vhosts
  - sh -e .travis/scripts/apache2-vhost.sh "$HOST"
  - sh -e .travis/scripts/apache2-vhost.sh "$IMGHOST"

  # PHP config
  - phpenv config-add .travis/travis.php.ini

  # MySQL
  - sudo cp config/phinx.yml.sample config/phinx.yml
  - sh -e .travis/scripts/mysql-init.sh "$DBNAME"

  # Restart Apache
  - sudo service apache2 reload

  # Selenium
  - sh -e .travis/scripts/selenium.sh
  - sleep 3

script:
  - ./vendor/bin/phpunit -c Tests/$BROWSER.phpunit.xml --stderr

after_script:
  - ./vendor/bin/coveralls -c .coveralls.yml -v
