language: php

php:
  - 5.5
  - 5.4

env:
  - ENVIRONMENT=test
  - DB=mysql

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS simplemappr_test;" -uroot; fi

script: phpunit --configuration config/phpunit.xml --coverage-text
