language: php

php:
  - 5.6

env:
  global:
    - HOST=www.simplemappr.local
    - IMGHOST=img.simplemappr.local
    - DBNAME=simplemappr_testing
    - BROWSER=firefox

addons:
  firefox: "41.0.1"
  hosts:
    - www.simplemappr.local
    - img.simplemappr.local
  apt:
    packages:
      - apache2
      - build-essential
      - libapache2-mod-fastcgi
      - php5-cli
      - php5-common
      - php5-dev
      - php5-fpm
      - php5-gd
      - php5-mysql
      - php5-curl
      - locales
      - gettext
      - autoconf
      - libjpeg-dev
      - libpng12-dev
      - libfcgi-dev
      - libgdal1-dev
      - libgdal-dev
      - libproj-dev
      - libxml2-dev
      - libgeos-dev
      - libcairo2-dev
      - libfribidi-dev
      - imagemagick
      - libgtk2.0-0
      - xvfb
      - unzip
      - openjdk-7-jre
      - libmagickwand-dev
      - curl
      - cmake

install:
  # ImageMagick
  - printf "\n" | pecl install imagick

  # MapServer installation
  - sh -e .travis/scripts/mapserver.sh

  # PHP configuration
  - phpenv config-add .travis/travis.php.ini
  - phpenv rehash

  # Install maps
  - sh -e .travis/scripts/maps.sh

  # Translations
  - sh -e .travis/scripts/locales.sh

  # Install Composer dependencies
  - composer self-update
  - composer install

before_script:
  # Create files
  - sudo touch log/logger.log
  - sudo cp config/conf.test.php config/conf.php

  # Directory permissions
  - sh -e .travis/scripts/permissions.sh

  # Apache web server config for vhosts
  - sudo cp -f .travis/apache2/www.simplemappr.local.conf /etc/apache2/sites-available/
  - sudo cp -f .travis/apache2/img.simplemappr.local.conf /etc/apache2/sites-available/
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/www.simplemappr.local.conf
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/img.simplemappr.local.conf
  - sudo a2ensite www.simplemappr.local
  - sudo a2ensite img.simplemappr.local
  - sudo a2enmod actions rewrite expires headers
  - sudo touch /usr/lib/cgi-bin/php5.fcgi

  # MySQL
  - sudo cp config/phinx.yml.sample config/phinx.yml
  - sh -e .travis/scripts/mysql-init.sh "$DBNAME"

  # Restart PHP-FCGI and Apache
  - phpenv rehash
  - sudo service php5-fpm restart
  - sudo service apache2 restart

  # Selenium
  - sh -e .travis/scripts/selenium.sh
  - sleep 3

script:
  - ./vendor/bin/phpunit -c Tests/$BROWSER.phpunit.xml --stderr

after_script:
  - ./vendor/bin/coveralls -c .coveralls.yml -v
  - sudo cat /var/log/apache2/error.log